a_lr: 0.0001
algo: ddpg
batch_size: 128
buffer_size: 60000
c_lr: 0.0001
episode_length: 200
epsilon: 0.5
epsilon_speed: 0.993
game_name: snakes_3v3
gamma: 0.9
load_model: false
load_model_run: 5
load_model_run_episode: 4000
log_dir: '20211013_211803'
max_episodes: 1000
model_episode: 0
output_activation: softmax
save_interval: 10
seed: 1
tau: 0.01
